"""Updated Freebie table and relationship columns in associated tables

Revision ID: 8806fa7f641d
Revises: 0b2ba6f06d01
Create Date: 2026-02-03 22:34:28.219506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8806fa7f641d'
down_revision = '0b2ba6f06d01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
